apiVersion: apps/v1
kind: Deployment
metadata:
  name: onion-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: onion-backend
  template:
    metadata:
      labels:
        app: onion-backend
    spec:
      containers:
        - name: backend
          image: vikasss0407/onionbackend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: backend-env