apiVersion: apps/v1
kind: Deployment

metadata:
  name: onion-frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: onion-frontend

  template:
    metadata:
      labels:
        app: onion-frontend

    spec:
      containers:

      - name: frontend

        image: 670099380890.dkr.ecr.eu-north-1.amazonaws.com/onionguard-frontend:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 80

        resources:

          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "300m"
            memory: "256Mi"